from pathlib import Path
p = Path('/home/ubuntu/entertainment-tracker/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('setSelectedItem={setSelectedItem} onAddMoment={() => { setPage("library"); setActiveType("All"); }} />', 'setSelectedItem={setSelectedItem} onAddMoment={() => { setPage("library"); setActiveType("All"); }} />')
s = s.replace('onFavorite={() => toggleFavorite(selectedItem)} isAuthenticated={isAuthenticated} onPlaytimeLogged=', 'onFavorite={() => toggleFavorite(selectedItem)} onSchedule={(value) => scheduleItem(selectedItem, value)} isAuthenticated={isAuthenticated} onPlaytimeLogged=', 1)
s = s.replace('function DetailModal({ item, onClose, onAdvance, onFavorite, isAuthenticated, onPlaytimeLogged }: { item: MediaItem; onClose: () => void; onAdvance: () => void; onFavorite: () => void; isAuthenticated: boolean; onPlaytimeLogged: (minutes: number) => void }) {', 'function DetailModal({ item, onClose, onAdvance, onFavorite, onSchedule, isAuthenticated, onPlaytimeLogged }: { item: MediaItem; onClose: () => void; onAdvance: () => void; onFavorite: () => void; onSchedule: (value: string) => void; isAuthenticated: boolean; onPlaytimeLogged: (minutes: number) => void }) {')
s = s.replace('<div className="detail-progress"><div className="progress-line"><ProgressBar value={item.progress} color={item.type === "Game" ? "#7358e8" : "#d986b3"} /><strong>{item.progress}%</strong></div><small>{item.detail}</small></div></div>', '<div className="detail-progress"><div className="progress-line"><ProgressBar value={item.progress} color={item.type === "Game" ? "#7358e8" : "#d986b3"} /><strong>{item.progress}%</strong></div><small>{item.detail}</small></div></div><label className="detail-schedule"><span><CalendarDays size={13} /> Scheduled date</span><input type="date" value={item.scheduledDate ?? ""} onChange={(event) => onSchedule(event.target.value)} /><small>{item.status === "Completed" ? "Completed item" : item.scheduledDate ? "Update or clear this date" : "Not scheduled yet"}</small></label>')
old = 'const events = items.filter((item) => item.scheduledDate).map((item) => { const date = new Date(`${item.scheduledDate}T00:00:00`); return { day: date.getDate(), date, label: item.title, type: item.type === "Game" ? "game" : "series", item }; }).filter((event) => event.date.getFullYear() === monthDate.getFullYear() && event.date.getMonth() === monthDate.getMonth());'
new = 'const todayKey = new Date().toISOString().slice(0, 10); const events = items.filter((item) => item.scheduledDate).map((item) => { const date = new Date(`${item.scheduledDate}T00:00:00`); const state = item.status === "Completed" ? "completed" : item.scheduledDate! < todayKey ? "overdue" : "planned"; return { day: date.getDate(), date, label: item.title, type: item.type === "Game" ? "game" : "series", state, item }; }).filter((event) => event.date.getFullYear() === monthDate.getFullYear() && event.date.getMonth() === monthDate.getMonth());'
if old not in s: raise SystemExit('calendar events target not found')
s = s.replace(old, new, 1)
s = s.replace('<span><i className="dot dot-purple" /> Games</span><span><i className="dot dot-pink" /> Series & movies</span>', '<span><i className="dot dot-purple" /> Planned</span><span><i className="dot dot-pink" /> Completed</span><span><i className="dot dot-yellow" /> Overdue</span>', 1)
s = s.replace('className={`calendar-event ${event.type}`}', 'className={`calendar-event ${event.type} ${event.state}`}')
s = s.replace('<strong>{event.label}</strong><span>{event.item.type} · {event.item.platform}</span>', '<strong>{event.label}</strong><span>{event.state === "overdue" ? "Overdue" : event.state === "completed" ? "Completed" : "Planned"} · {event.item.type}</span>')
s = s.replace('<strong>{events.length ? `${events.length} scheduled ${events.length === 1 ? "moment" : "moments"}` : "Nothing scheduled yet"}</strong>', '<strong>{events.length ? `${events.length} ${events.length === 1 ? "moment" : "moments"} this month` : "Nothing scheduled yet"}</strong>')
p.write_text(s)
