from pathlib import Path

p = Path('/home/ubuntu/entertainment-tracker/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('  const [showAdd, setShowAdd] = useState(false);', '  const [showAdd, setShowAdd] = useState(false);\n  const [promotingItem, setPromotingItem] = useState<CemeteryItem | null>(null);')
s = s.replace('  const addItem = () => {\n    if (!newItem.title.trim()) {', '  const addItem = () => {\n    if (promotingItem) {\n      promoteMutation.mutate({ id: promotingItem.id, item: { ...newItem, title: newItem.title.trim() || promotingItem.title || "Untitled", favorite: false } });\n      setShowAdd(false);\n      setPromotingItem(null);\n      return;\n    }\n    if (!newItem.title.trim()) {')
s = s.replace('onPromote={(item) => { const type = item.category === "Game" ? "Game" : item.category === "Movie" ? "Movie" : "Game"; setNewItem({ title: item.title, type, status: type === "Game" ? "Want to play" : "Want to watch", genre: item.category ?? "Adventure", platform: "", externalId: undefined, image: undefined, detail: item.note ?? undefined, metadataJson: undefined }); setShowAdd(true); }}', 'onPromote={(item) => { const type = item.category === "Game" ? "Game" : item.category === "Movie" ? "Movie" : "Game"; setPromotingItem(item); setNewItem({ title: item.title, type, status: type === "Game" ? "Want to play" : "Want to watch", genre: item.category ?? "Adventure", platform: "", externalId: undefined, image: undefined, detail: item.note ?? undefined, metadataJson: undefined }); setShowAdd(true); }}')
s = s.replace('onClose={() => setShowAdd(false)} onAdd={addItem}', 'onClose={() => { setShowAdd(false); setPromotingItem(null); }} onAdd={addItem}')
marker = 'function AddModal('
components = '''function Cemetery({ items, onQuickAdd, onPromote }: { items: CemeteryItem[]; onQuickAdd: () => void; onPromote: (item: CemeteryItem) => void }) {
  const [category, setCategory] = useState<"All" | CemeteryCategory>("All");
  const visible = items.filter((item) => category === "All" || item.category === category);
  const tabs: ("All" | CemeteryCategory)[] = ["All", "Movie", "Game", "Software", "Study", "Other"];
  return <div className="page-stack"><section className="cemetery-intro"><div><span className="eyebrow accent-eyebrow"><Camera size={13} /> A soft place to keep the unknown</span><h2>Screenshot <em>Cemetery.</em></h2><p>Save anything that caught your eye. No title, category, calendar, or commitment required.</p></div><button className="primary-button" onClick={onQuickAdd}><Camera size={16} /> Quick Add</button></section><div className="library-toolbar"><div className="filter-tabs cemetery-tabs">{tabs.map((tab) => <button key={tab} className={category === tab ? "selected" : ""} onClick={() => setCategory(tab)}>{tab}</button>)}</div><span className="cemetery-count">{visible.length} saved</span></div>{visible.length ? <section className="cemetery-grid">{visible.map((item) => <article className="cemetery-card" key={item.id}><div className="cemetery-card-head"><span className="cemetery-pin"><Camera size={15} /></span><span className="cemetery-date">{item.createdAt ? new Date(item.createdAt).toLocaleDateString() : "Just now"}</span></div><h3>{item.title || "Untitled"}</h3>{item.note && <p>{item.note}</p>}{item.sourceLink && <a href={item.sourceLink} target="_blank" rel="noreferrer"><Link2 size={13} /> Open source</a>}<div className="cemetery-card-foot"><span className={`category-tag ${item.category?.toLowerCase() ?? "uncategorized"}`}>{item.category ?? "Uncategorized"}</span><button className="small-action" onClick={() => onPromote(item)}>Add as item <ArrowUpRight size={13} /></button></div></article>)}</section> : <div className="empty-state"><Camera size={28} /><h3>Your cemetery is quiet</h3><p>Use Quick Add to save a link or screenshot moment without deciding what it is yet.</p><button className="dark-button" onClick={onQuickAdd}><Plus size={15} /> Save something</button></div>}</div>;
}

function QuickAddModal({ link, defaultCategory, onClose, onSave, onSetDefault, saving }: { link: string; defaultCategory: CemeteryCategory | null; onClose: () => void; onSave: (payload: { title: string; category: CemeteryCategory | null; note: string; sourceLink: string }) => void; onSetDefault: (category: CemeteryCategory | null) => void; saving: boolean }) {
  const [sourceLink, setSourceLink] = useState(link);
  const [note, setNote] = useState("");
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState<CemeteryCategory | null>(defaultCategory);
  const cats: { value: CemeteryCategory; icon: typeof Gamepad2; tint: string }[] = [{ value: "Movie", icon: Clapperboard, tint: "movie" }, { value: "Game", icon: Gamepad2, tint: "game" }, { value: "Software", icon: Command, tint: "software" }, { value: "Study", icon: BookOpen, tint: "study" }, { value: "Other", icon: Tag, tint: "other" }];
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card quick-add-card" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow accent-eyebrow"><Camera size={13} /> Screenshot Cemetery</span><h2>Save without deciding.</h2></div><button className="icon-button subtle" onClick={onClose}><X size={17} /></button></div><p className="quick-add-copy">Keep a link or thought here now. You can identify and promote it later — or leave it here forever.</p><label className="quick-field"><span>Shared link or text</span><input autoFocus value={sourceLink} onChange={(event) => setSourceLink(event.target.value)} placeholder="Paste a TikTok, Reel, or any link" /></label><label className="quick-field"><span>Optional note</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="What caught your eye?" rows={3} /></label><label className="quick-field"><span>Optional title</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Leave blank for Untitled" /></label><div className="quick-category-label"><span>Category, if you know it</span><small>Tap ★ to make a personal default</small></div><div className="quick-category-grid">{cats.map(({ value, icon: Icon, tint }) => <div className={`quick-category ${tint} ${category === value ? "selected" : ""}`} key={value}><button onClick={() => setCategory(category === value ? null : value)}><Icon size={17} /><span>{value}</span></button><button className="default-star" aria-label={`Set ${value} as default`} onClick={() => { const next = defaultCategory === value ? null : value; onSetDefault(next); setCategory(next); }}><Star size={13} fill={defaultCategory === value ? "currentColor" : "none"} /></button></div>)}</div><div className="quick-add-actions"><button className="text-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving} onClick={() => onSave({ title, category, note, sourceLink })}>{saving ? <Loader2 size={15} className="spin" /> : <Camera size={15} />} Save to Cemetery</button></div></div></div>;
}

'''
if marker not in s:
    raise SystemExit('AddModal marker not found')
s = s.replace(marker, components + marker, 1)
p.write_text(s)
