from pathlib import Path
import re
p = Path('/home/ubuntu/entertainment-tracker/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('onRefreshMetadata, refreshing }: { items: MediaItem[]; activeType:', 'onRefreshMetadata, refreshing, onSchedule }: { items: MediaItem[]; activeType:')
s = s.replace('onRefreshMetadata: () => void; refreshing: boolean }) {', 'onRefreshMetadata: () => void; refreshing: boolean; onSchedule: (item: MediaItem, value: string) => void }) {', 1)
old = '<p>{item.detail}</p>{item.progress > 0 &&'
new = '<p>{item.detail}</p><label className="schedule-field" onClick={(event) => event.stopPropagation()}><CalendarDays size={12} /><span>{item.scheduledDate ? "Scheduled" : "Schedule"}</span><input type="date" value={item.scheduledDate ?? ""} onChange={(event) => onSchedule(item, event.target.value)} /></label>{item.progress > 0 &&'
if old not in s:
    raise SystemExit('library insertion target not found')
s = s.replace(old, new, 1)
start = s.index('function CalendarPage(')
end = s.index('\nfunction Insights(', start)
calendar = '''function CalendarPage({ monthName, monthDate, monthOffset, setMonthOffset, calendarCells, items, setSelectedItem, onAddMoment }: { monthName: string; monthDate: Date; monthOffset: number; setMonthOffset: (value: number) => void; calendarCells: (number | null)[]; items: MediaItem[]; setSelectedItem: (item: MediaItem) => void; onAddMoment: () => void }) {
  const events = items.filter((item) => item.scheduledDate).map((item) => { const date = new Date(`${item.scheduledDate}T00:00:00`); return { day: date.getDate(), date, label: item.title, type: item.type === "Game" ? "game" : "series", item }; }).filter((event) => event.date.getFullYear() === monthDate.getFullYear() && event.date.getMonth() === monthDate.getMonth());
  const monthLabel = monthDate.toLocaleDateString("en-US", { month: "short" }).toUpperCase();
  return <div className="page-stack"><section className="calendar-intro"><div><span className="eyebrow accent-eyebrow"><CalendarDays size={13} /> A soft plan</span><h2>Make time for <em>good stories.</em></h2><p>See the library items you have scheduled, all in one place.</p></div><div className="calendar-legend"><span><i className="dot dot-purple" /> Games</span><span><i className="dot dot-pink" /> Series & movies</span></div></section><section className="calendar-layout"><div className="calendar-card"><div className="calendar-head"><button className="icon-button subtle" onClick={() => setMonthOffset(monthOffset - 1)}><ChevronLeft size={17} /></button><div><strong>{monthName}</strong><span>{monthDate.getFullYear()} · your scheduled items</span></div><button className="icon-button subtle" onClick={() => setMonthOffset(monthOffset + 1)}><ChevronRight size={17} /></button></div><div className="weekday-row">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarCells.map((day, index) => { const dayEvents = events.filter((entry) => entry.day === day); return <div className={`calendar-day ${day === new Date().getDate() && monthOffset === 0 ? "today" : ""} ${!day ? "blank" : ""}`} key={`${day}-${index}`}>{day && <><span className="day-number">{day}</span>{dayEvents.map((event) => <button key={event.item.id} className={`calendar-event ${event.type}`} onClick={() => setSelectedItem(event.item)}><i />{event.label}</button>)}</>}</div>; })}</div></div><aside className="calendar-aside"><div className="aside-title"><span className="eyebrow">This month</span><strong>{events.length ? `${events.length} scheduled ${events.length === 1 ? "moment" : "moments"}` : "Nothing scheduled yet"}</strong></div>{events.map((event) => <button className="event-row" key={event.item.id} onClick={() => setSelectedItem(event.item)}><div className={`event-day ${event.type}`}><strong>{event.day}</strong><span>{monthLabel}</span></div><div><strong>{event.label}</strong><span>{event.item.type} · {event.item.platform}</span></div><ChevronRight size={15} className="muted-icon" /></button>)}<button className="add-calendar-button" onClick={onAddMoment}><CirclePlus size={15} /> Schedule from library</button></aside></section></div>;
}'''
s = s[:start] + calendar + s[end:]
s = s.replace('<Library items={filteredItems} activeType={activeType} setActiveType={setActiveType} search={search} setSearch={setSearch} advanceItem={advanceItem} toggleFavorite={toggleFavorite} setSelectedItem={setSelectedItem} onRefreshMetadata={refreshAllMetadata} refreshing={refreshing} />', '<Library items={filteredItems} activeType={activeType} setActiveType={setActiveType} search={search} setSearch={setSearch} advanceItem={advanceItem} toggleFavorite={toggleFavorite} setSelectedItem={setSelectedItem} onRefreshMetadata={refreshAllMetadata} refreshing={refreshing} onSchedule={scheduleItem} />')
s = s.replace('<CalendarPage monthName={monthName} monthOffset={monthOffset}', '<CalendarPage monthName={monthName} monthDate={monthDate} monthOffset={monthOffset}')
s = s.replace('calendarCells={calendarCells} items={items} setSelectedItem={setSelectedItem} />', 'calendarCells={calendarCells} items={items} setSelectedItem={setSelectedItem} onAddMoment={() => { setPage("library"); setActiveType("All"); }} />')
p.write_text(s)
