from pathlib import Path

path = Path('/home/ubuntu/entertainment-tracker/client/src/pages/Home.tsx')
text = path.read_text()
old = '<div className="metadata-tags">{richMetadata.tags.slice(0, 6).map((tag) => <span key={tag}>{tag}</span>)}</div> : null}</section>}{item.type === "Series" ? <section className="episode-panel"><div className="episode-panel-head">'
new = '''<div className="metadata-tags">{richMetadata.tags.slice(0, 6).map((tag) => <span key={tag}>{tag}</span>)}</div> : null}</section>}{richMetadata && <section className="metadata-extras">{richMetadata.overview && <p className="metadata-overview">{richMetadata.overview}</p>}{richMetadata.cast?.length ? <div className="cast-row"><span className="eyebrow">Cast</span><div>{richMetadata.cast.slice(0, 6).map((person) => <span className="cast-chip" key={`${person.name}-${person.character}`}><strong>{person.name}</strong><small>{person.character}</small></span>)}</div></div> : null}{richMetadata.screenshots?.length ? <div className="screenshot-strip"><span className="eyebrow">Screenshots</span><div>{richMetadata.screenshots.slice(0, 6).map((source) => <img key={source} src={source} alt="" />)}</div></div> : null}{richMetadata.trailers?.length ? <div className="trailer-links"><span className="eyebrow">Trailers</span><div>{richMetadata.trailers.slice(0, 3).map((trailer) => <a key={trailer.key} href={`https://www.youtube.com/watch?v=${trailer.key}`} target="_blank" rel="noreferrer"><Play size={12} /> {trailer.name}</a>)}</div></div> : null}</section>}{item.type === "Series" ? <section className="episode-panel"><div className="season-nav">{richMetadata?.seasons?.length ? <><span className="eyebrow"><ListChecks size={13} /> Season</span><select value={selectedSeason ?? richMetadata.seasons[0].seasonNumber} onChange={(event) => setSelectedSeason(Number(event.target.value))}>{richMetadata.seasons.map((season) => <option key={season.seasonNumber} value={season.seasonNumber}>{season.name || `Season ${season.seasonNumber}`} · {season.episodeCount} eps</option>)}</select></> : null}</div><div className="episode-panel-head">'''
if old not in text:
    raise SystemExit('detail UI insertion marker not found')
text = text.replace(old, new, 1)
text = text.replace('<button className="text-button" onClick={onClose}>Close</button><button className="dark-button" onClick={onAdvance}>', '<button className="text-button" onClick={onClose}>Close</button>{item.id < 1000000000000 && item.externalId && <button className="small-action" onClick={() => refreshMutation.mutate({ id: item.id })} disabled={refreshMutation.isPending}><RefreshCw size={13} className={refreshMutation.isPending ? "spin" : ""} /> Refresh</button>}<button className="dark-button" onClick={onAdvance}>', 1)
path.write_text(text)
